### ISSUE TITLE
Issue with Exception::Class version 1.43

### ISSUE THREAD

**Issue by emanissp** [houseabsolute/Exception-Class#12]
We are currently using perl 5.14 and trying to upgrade 5.24. 

5.14 uses  Exception::Class version 1.32 upgrading to perl 5.24 Exception::Class version 1.43

5.14 our applciation code is working fine for exceptions, 5,24 it says pretty can't be found ( see our application code below) . 

After some research we found in  Exception::Class version 1.43 has the code snippet    
 ( my $filename = "$subclass.pm" ) =~ s{::}{/}g;
    $INC{$filename} = __FILE__;.

If we comment INC, it is working fine 5.24. 

Can you tell what is the purpose of the following code snippet in 1.43

 ( my $filename = "$subclass.pm" ) =~ s{::}{/}g;
    $INC{$filename} = __FILE__;.

-----------------------------------------
OUR Application code is as below
-------------------------------------------------------
package Application::Exception;

use Data::Dump qw( dd pp );

use Exception::Class
( 'JobRunner::Core::Util::Exception' => {
      description => 'generic base class for JobRunner::Core::Util exception',
  },
);

sub pretty
{
  my ( $e ) = @_;

  my @msg = (
    sprintf( "File '%s' threw exception at line %d:\n\t%s",
             $e->file(), $e->line(), $e->error() )
  );

  for my $field ( sort $e->Fields() )
  {
    my $val = $e->$field();
    if ( defined $val )
    {
      push @msg, sprintf( "\t%s: %s"
                        , $field
                        , pp( $val )
                        );
    }
  }

  return join( "\n", @msg );
} # pretty()

---------------------------
package Application::Files;

use Data::Dump qw( dd pp );

use constant EXCEPTION => __PACKAGE__ . '::Exception';
use Exception::Class (
  'Application::Exception',
  __PACKAGE__ . '::Exception' => {
      isa    => 'JobRunner::Core::Util::Exception',
      fields => [ qw( from_dir match ) ]
  },
);

use Moose;
with 'Application::FileList';
with 'Application::Task';

has 'list' => ( is       => 'rw'
              , isa      => 'ArrayRef'
              );

sub BUILD
{
  my $self = shift;

  return if ( $self->do_check() );

  $self->list( $self->get_file_list() );

  if ( my $match = $self->match() )
  {
    if ( $match eq 'all' && ! $self->matched_all() )
    {
      my $err = "no matches for file spec '" . join( "', '", $self->unmatched() ) . "'";
      EXCEPTION->throw(
        error    => $err,
        from_dir => $self->from_dir(),
        match    => 'all',
      );
    }
    elsif ( $match eq 'one' && ! $self->matched_one() )
    {
      my $err = "no matches for file spec '" . join( "', '", $self->unmatched() ) . "'";
      EXCEPTION->throw(
        error    => $err,
        from_dir => $self->from_dir(),
        match    => 'one',
      );
    }
  }
} # BUILD()

sub do_check
{
  my $self = shift;

  if ( my $match = $self->match() )
  {
    EXCEPTION->throw( "match value must be either 'all' or 'one'" )
      unless ( $match eq 'all' || $match eq 'one' );
  }

  return $self->check();
} # do_check

1;

**Comment by autarch** [comment]
The adding of classes to `%INC` is described in the Changes entry for 1.42:

- Generated exception classes are now added to %INC. If you subclass a generated class with "use base" then base.pm will no longer attempt to load the requested class. Patch by Todd Rinaldo. PR #8.

This is a helpful change for a common use case.

GitHub issues aren't a forum for support questions, and there's no bug here so I'm closing this issue.
