### ISSUE TITLE
Info: Pattern that cannot be installed depending on cpan settings

### ISSUE THREAD

**Issue by twata1** [houseabsolute/Exception-Class#15]
Hello,

Depending on the configuration of cpan, there is a pattern that cannot be installed, as shown below.

Strawberry Perl 5.32.1 64 bit with cpan 2.29 settings:

```
C:\home\sunnyday1>cpan Exception::Class
Loading internal logger. Log::Log4perl recommended for better logging
CPAN: CPAN::SQLite loaded ok (v0.219)
Database was generated on Sun, 12 Dec 2021 03:10:46 GMT
Running install for module 'Exception::Class'
CPAN: Digest::SHA loaded ok (v6.02)

Warning: checksum file 'C:\Strawberry\cpan\sources\authors\id\D\DR\DROLSKY\CHECKSUMS' not conforming.

The cksum does not contain the key 'cpan_path' for 'Exception-Class-1.45.tar.gz'.
Proceed nonetheless? [no] no
Aborted.


C:\home\sunnyday1>
```

Thank you,

**Comment by autarch** [comment]
This looks like it's either an issue with Strawberry Perl, CPAN/PAUSE, or the CPAN distribution. But I've never seen this and I have no idea what's going on. I'd suggest starting with [the CPAN distribution](https://metacpan.org/dist/CPAN), since that seems to be what's giving the error.

**Comment by twata1** [comment]
Thanks for the reply.
I will try to ask in the [Request Tracker ](https://rt.cpan.org/Public/Dist/Display.html?Name=CPAN)of the CPAN distribution.

**Comment by twata1** [comment]
I removed 'C:\Strawberry\cpan\sources\authors\id\D\DR\DROLSKY\CHECKSUMS' due to [RT#140449](https://rt.cpan.org/Public/Bug/Display.html?id=140449) and could install Exception::Class.

Thank you for the suggestion!
